workflows:
  YOMA-Release:
    name: YOMA Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        BUNDLE_ID: com.yoma.app
        XCODE_WORKSPACE: Runner.xcworkspace
        XCODE_SCHEME: Runner

      groups:
        - YOMA_PROJECT_BASE
        - yoma_signing_certificates
        - yoma_ios_credentials
        - google_play_credentials
        - android_signing_debug

    scripts:
      - name: 🧹 Limpeza e dependências
        script: |
          flutter clean
          flutter pub get

      - name: 🔐 Importar certificados e perfis iOS
        script: |
          echo $CERTIFICATE_P12_BAS | base64 --decode > Certificates.p12
          echo $PROVISIONING_PROFI | base64 --decode > Profile.mobileprovision

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          security create-keychain -p "" build.keychain
          security import Certificates.p12 -k build.keychain -P "$CERTIFICATE_PASSWC" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

      - name: 🛠 Build Android (AAB)
        script: |
          flutter build appbundle --release

      - name: 🍎 Build iOS (IPA)
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/Runner/ExportOptions.plist

    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_JSON
        track: internal
        in_app_update_priority: 0
        submit_as_draft: true

      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
