// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi1445YNIM-hNzZXWwgpxoLv96Pa_c8pI',
    appId: '1:223510929312:web:2409ab5cdb923232960ec5',
    messagingSenderId: '223510929312',
    projectId: 'guardian-angel-2e95t',
    authDomain: 'guardian-angel-2e95t.firebaseapp.com',
    storageBucket: 'guardian-angel-2e95t.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHVdqPrEQgwCCb0ToxXphEAAQ-UAvdIF4',
    appId: '1:223510929312:android:8d82e9f8ee23d6ae960ec5',
    messagingSenderId: '223510929312',
    projectId: 'guardian-angel-2e95t',
    storageBucket: 'guardian-angel-2e95t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVu63X3CjlhW4KaxDgYt3kd4tflMH9Z0Y',
    appId: '1:223510929312:ios:27471ca53beddf0f960ec5',
    messagingSenderId: '223510929312',
    projectId: 'guardian-angel-2e95t',
    storageBucket: 'guardian-angel-2e95t.firebasestorage.app',
    iosBundleId: 'com.yoma.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVu63X3CjlhW4KaxDgYt3kd4tflMH9Z0Y',
    appId: '1:223510929312:ios:27471ca53beddf0f960ec5',
    messagingSenderId: '223510929312',
    projectId: 'guardian-angel-2e95t',
    storageBucket: 'guardian-angel-2e95t.firebasestorage.app',
    iosBundleId: 'com.yoma.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi1445YNIM-hNzZXWwgpxoLv96Pa_c8pI',
    appId: '1:223510929312:web:f5e144f0fd556660960ec5',
    messagingSenderId: '223510929312',
    projectId: 'guardian-angel-2e95t',
    authDomain: 'guardian-angel-2e95t.firebaseapp.com',
    storageBucket: 'guardian-angel-2e95t.firebasestorage.app',
  );
}
